name: CI-CD Workflow

#Defaults of workflow for each run, will use bash shell
defaults:
  run:
    shell: bash
    working-directory: 02remote-modules/dev

#Trigger
on:
  push:

jobs:
  tf_worflow:
    runs-on: ubuntu-latest
    name: "TF Workflow"

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Init & Validate| Base Infra
        run: |
          terraform init
          terraform validate

      - name: Plan | Base Infra
        run: |
          terraform plan -out tfplan

      - name: Apply | Base Infra
        run: |
          terraform apply tfplan
          echo "🍏 This job's status is ${{ job.status }}."
